# Generated by Django 5.2.3 on 2025-06-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata_viewer.proyecto')),
            ],
        ),
    ]
